name: ecommerce
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none' 

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  flutter_slidable: ^2.0.0
  flutterfire_ui: ^0.4.3+4
  image_picker: ^0.8.5+3
  lottie: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/img/
    - assets/icon/
    - assets/anim/
    - assets/font/
  