name: ecommerce
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none' 

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  